name: Deploy Laravel to cPanel/hPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install PHP dependencies
    - name: Install PHP dependencies
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, exif, bcmath, intl
        tools: composer
    - run: composer install --no-dev --optimize-autoloader
      working-directory: ./src  # Ensure this points to your Laravel folder

    # Step 3: Build Frontend (Vue, Inertia, Tailwind)
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: |
        npm ci
        npm run prod
      working-directory: ./src  # Ensure this points to your Laravel folder

    # Step 4: Upload to Server
    - name: Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ftp.coderpirate.com
        username: admin@coderpirate.com
        password: Admin@1332
        local-dir: ./src  # Ensure this points to your Laravel folder
        server-dir: /public_html

    # Step 5: Clear Cache and Migrate Database
    - name: Run Laravel Artisan Commands
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan migrate --force
      env:
        APP_ENV: production
      working-directory: ./src  # Ensure this points to your Laravel folder
